### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by casperankinen** [daphreak66/TweenSharp#1]
I was running a build for iOS and it threw an error in TSKeywordParser.cs as it contains a reference to UnityEditor and that can't go into a build.

I just ended up doing the following to get the build to run but I don't feel like that was the real solution:

    #if UNITY_EDITOR
    	using UnityEditor;
    #endif

**Comment by technyon** [comment]
Hi,

actually this import isn't necessary at all, it's just my IDE that sometimes likes to include it. I've removed it, thanks for letting me know.
