### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by casperankinen** [daphreak66/TweenSharp#2]
Hi Jan,

I started using this library for the same reason you made it, I have come over to Unity from Flash and loved TweenMax.

One feature I really liked in TweenMax was tint or being able to transition between colors. I thought of trying to make a plugin but I realise that I'm limited by a few things. I feel like there's two ways to do it, either use the Color.Lerp tool in Unity and just use TweenSharp to control the 0 to 1 value it needs or alternately separate R, G, B, A, values (but to make it useful, you generally want to pass a single color value).

The problem is both of those need to edit the main TweenSharp library. To use Color.Lerp, the start and end color values need to be stored somewhere other than the dictionary (since Lerp is doing the Interpolating). Or with R, G, B, A plugins, it would first need a way of parsing the hex or Color object into those values.

Wasn't sure on your thoughts around that because the current way the plugins are handled seems pretty clean.

**Comment by technyon** [comment]
Hi,

I've had a similar thought. TweenMax allows to pass many parameters to a plugin because plugins can receive objects, not only floats. Going to an untyped datatype obviously isn't very clean, and there's a performance penalty for boxing/unboxing. In this case you could convert the hex value to a float and pass it.

One way that comes to mind would be to allow plugins to define a second parameter that allows to pass objects. So the main parameter would be a float, the second one an object.

I need to think about this though, Id like to keep it clean.

**Comment by technyon** [comment]
Hi,

I finally got around to have a look into the issue. I think I've found a solution that's clean and yet fits the TweenMax approach.

You can now pass either a float, or an object of type TSTweenParams. You pass the target value (float) in the constructor of the object, so TweenSharp has something to work with. You can inherit from TSTweenParams and add any number of of parameters. The tween plugin base class TSPlugin now has a member of type TSTweenParams, which will be automatically populated with the object passed to TweenSharp.

I made a quick example plugin to tween text.

The data object:

`    public class TSTestParams : TSTweenParams
    {
        public string txt;
        
        public TSTestParams(float value, string txt) : base(value)
        {
            this.txt = txt;
        }
    }
`

And the tween plugin using the data:

`
    public class TSPluginTest : TSTransformPlugin
    {
        private readonly string PROPERTY_NAME = "test";

        private float value = 0f;
        
        public override float Value
        {
            get { return value; }
            set
            {
                this.value = value;
                string s = ((TSTestParams) parameters).txt;
                s = s.Substring(0, (int)((float) s.Length * value));

                Text txt = (Target as GameObject).GetComponent<Text>();
                txt.text = s;
            }
        }

        public override string PropertyName
        {
            get { return PROPERTY_NAME; }
        }
    }
`

Finally, this is how you start the tween:

`
		tweenSharp1 = TweenSharp.To(gameObject, 5f, new {
			test = new TSTestParams(1f, "Nunc pharetra, elit ut lobortis vehicula, nisl metus tincidunt mauris, vitae accumsan arcu justo sit amet odio. "),
			ease = Linear.EaseNone
		});
`

**Comment by casperankinen** [comment]
Hi, it's taken me a while to get the time to experiment with this. This is great! I haven't implemented a colour plugin yet but I did get your example working and played with using this on the fillAmount of circular animations. Works well!

If anyone else reads this and is stuck, you also need to include your new plugin in the TSPluginManager.cs class so you don't get the 'Property "test" isn't found on object Gameobject' error.

**Comment by technyon** [comment]
Hi, thanks I'll see to add this to the documentation. You can also call the static static TSPluginManager.Activate method your plugin.
