### ISSUE TITLE
Setting Properties prior to start and onCompleteParams example

### ISSUE THREAD

**Issue by casperankinen** [daphreak66/TweenSharp#3]
I've been using TweenSharp a bit, thank you and I've run into a few problems,

I want to have an object that fades out from 100% alpha each time an action is called. I've tried a TweenSharp with a *0f* time setting but that doesn't do it. At the moment that's 3 lines of code to set (Color object from the target, set the Alpha property, then reapply it to the target. Am I missing how to set this, like TweenMax.Set or a 0 timed Tween?

Another question is could you provide an example in the wiki of how to pass a simple variable like an int or string through onCompleteParams? (I'm not that clear on the syntax of C# to do that.)

Cheers!

**Comment by technyon** [comment]
A tween with a duration of 0f should do it, I've used it myself. Can you provide a code sample?

Regarding your second question:

```
string s;

new TweenSharp(0f, obj, new {
  onComplete = new Action<object>(HandlerMethod),
  onCompleteParams = (object)s
});

void HandlerMethod(object o) {
  string s = o as string;
}
```

I've also noticed I need to update the documentation, onCompleteArg is not used anymore.

**Comment by casperankinen** [comment]
Thanks so much for that! Really helps me.

Here's a sample of my code where I've been trying to set the alpha to 1 then immediately fade it out.
TweenSharp correctTweenStart= new TweenSharp( correctImage, 0f ,new{ alpha=1f });
TweenSharp correctTween= new TweenSharp( correctImage, .5f ,new{ alpha=0f, onComplete = new Action (transitionToNextQuestion) });

**Comment by technyon** [comment]
Ah OK I get it, you do both in the same frame. You'd indeed need a TweenSharp.Set() method for this to work. I'll see if I can implement it, unfortunately I'm currently sick.

In the meantime, I think the easiest way to do it is to put an onComplete method into the first tween which calls a method that triggers the second tween.

**Comment by casperankinen** [comment]
Ok yes, that's probably the best way to do it! Thanks for your time.
