### ISSUE TITLE
InstantiateOnLoad with GameObject Singleton

### ISSUE THREAD

**Issue by casperankinen** [daphreak66/TweenSharp#4]
Have you got any tips on how to implement TweenSharp with the new InstantiateOnLoad when you're using a Singleton GameObject to store data and swtich between scenes?

I have a scene with a TweenSharp inside it that when tested alone, works just fine. if I load my scene in with the Singleton, TweenSharp isn't firing.

My old setup was to have TSScheduler on my first scene that loads (and that scene initializes my Singleton) and any subsequent scenes work from there (with no TSScheduler on their GameManagers). If I add a TweenSharp to either my first scene or my singleton both work but subsequent scenes that are loaded don't fire.

**Comment by technyon** [comment]
Hi,

You can still do it the old way by disabling the InstantiateOnLoad functionality. There's now a settings object in TweenSharps Resource directory, just uncheck "InstantiateOnLoad".

I can look into the issue though, can you give me an example project to reproduce this behavior?

**Comment by casperankinen** [comment]
Hi, ok I've spent quite a while reading up on and experimenting with different persistent object techniques. I had originally been relying on a Singleton GameObject to store scores between scenes but that would result in initializing the TSScheduler each time a scene loaded and throwing the exception. After some further reading, I realised it's better to use one scene that you additively load and unload other scenes from.

I've made a test project here with that setup:
https://www.dropbox.com/sh/joljw20crtc8i0b/AAAAvSU8zVgBcBBifDj5N9nea?dl=0

I've also put a script in so that CMD/CTRL+SHIFT+0 will test it from the correct scene.

TweenSharp works with the "Instantiate on Load" activated or by putting a TSSchedule.cs script added to that first scene loaded.

I've run into a different issue though. If a tween is playing when a scene is unloaded then TweenSharp stops working (basically because the object TweenSharp is operating on has been destroyed). You can see that within the project above.

Since I can't see something like a KillAllActiveTweens action within TweenSharp right now, I have two options, which are to wait until the tween stops playing using OnComplete and then allow the unload to happen or pause it and then let the unload occur. The latter seems a bit simpler yet this means I need to put all of my tweens into a List as I create them and run through that prior to the unload. Would love any other suggestions on this.

**Comment by technyon** [comment]
Hi,

Thanks I'll check the project.

About the second issue, I know this is different from Flash. TweenMax can happily work on any MovieClip that's not being used anymore (and there's no real way to destroy a MovieClip, except for dereferencing it). You can call the TweenSharp.Kill() method on each tween working on that GameObject / MonoBehaviour, after that it's safe to destroy. You're right though, a KillAllActiveTweens method would be nice, I'll see what I can do about it.

**Comment by casperankinen** [comment]
Thanks! In the meantime I've just used that Kill() method like this within the script where I'm creating my tweens. That gets me around the problem right now.

```
private List<TweenSharp> tweenList = new List<TweenSharp>();
tweenList.Add(new TweenSharp(......));

function UnloadScene(){
 foreach(TweenSharp tween in tweenList){
  tween.Kill();
}
SceneManager.UnloadSceneAsync(....);
}
```

**Comment by technyon** [comment]
I've addressed both problems. If you use the InitializeOnLoad functionality, TSScheduler now persists itself over scenes using DontDestroyOnLoad, and there's a KillTweensOf method now. I'd say though that it's better to manage running tweens in your code instead of calling KillTweensOf. First, if you manage it yourself, you know better what's going on. Second, KillTweensOf has to iterate over all running tweens and delayed calls, which could be slow if many are running.

**Comment by casperankinen** [comment]
Wow that's great! Thank you for being so helpful on this.

**Comment by technyon** [comment]
I'm glad we could fix those points.
